Correct language re jetting.
urbit/docs pull request #928
Opened 2020-08-13 19:38 UTC by sigilante

Cell composition, not list composition, is referred to by `u3nc` _y amigos_.

2019-07-31 21:57 UTC, rmariani commented
Thanks for pointing this out, Matilde.

2020-10-29 21:32 UTC, syzygyzer commented
I don't know the details on jets. @baudtack ?

2020-12-01 23:17 UTC, baudtack requested changes

2020-12-06 17:28 UTC, sigilante commented on tutorials/vere/jetting.md
> +If you need to return a longer collection, you can compose your own.  Look
Hecho.

2020-12-06 17:28 UTC, sigilante commented on tutorials/vere/jetting.md
> +is wrong and will result in a dojo error because you are returning a single atom, instead of a cell containing three atoms.
Factum est.

2021-01-05 01:37 UTC, baudtack approved these changes

2021-01-05 01:38 UTC, merged

2021-06-29 18:33 UTC, baudtack commented
No longer an issue. The real way to fix issues is to just wait two years.